atom-community/atom

.github/pull.yml
This helps us keep the master branch up to date with the upstream master branch
=> add pull bot configuration

script/vsts/get-release-version.js, script/vsts/platforms/macos.yml, script/vsts/platforms/windows.yml
Fixes https://github.com/atom-ide-community/atom/issues/8
Adds a `SHOULD_SIGN` env variable which allows skipping code signing when you are on the release branch. This allows building Atom without purchasing a code signing certificate. It is meant to facilitate the process of testing atom in the forks (particularly atom-community/atom)
Requires setting `SHOULD_SIGN=true` as an environment variable inside Azure.
N/A; this is a developer-facing change, not an end-user facing change.
Upstream PR: https://github.com/atom/atom/pull/21023
=> Makes code-sign optional 

script/vsts/platforms/linux.yml, script/vsts/platforms/macos.yml, script/vsts/platforms/windows.yml
<details><summary>Requirements for Adding, Changing, or Removing a Feature (from template)</summary>
* The pull request must contribute a change that has been endorsed by the maintainer team. See details in the template below.
* The pull request must update the test suite to exercise the updated functionality. For guidance, please see <https://flight-manual.atom.io/hacking-atom/sections/writing-specs/>.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see <https://github.com/atom/.github/tree/master/CONTRIBUTING.md#pull-requests>. …
=> CI: Use Cache@2 task in place of Lighthouse

script/vsts/release-branch-build.yml
Release branch builds are triggered by making pull requests
This prevents the release builds to be triggered by a pull request.
Setting the option in Azure UI, but that reduces the reproducibility of the jobs for the forks. Atom should avoid setting the pipeline options in the Azure UI as much as possible because that is hidden from others who do not have access.
N/A;
=> no PR triggers on release builds

script/vsts/platforms/cache.yml, script/vsts/platforms/linux.yml, script/vsts/platforms/macos.yml, script/vsts/platforms/windows.yml
This refactors cache steps into a template. 
Ran CI with these changes.
N/A
=> Cache templates

script/vsts/get-release-version.js, script/vsts/lib/release-notes.js, script/vsts/nightly-release.yml, script/vsts/pull-requests.yml, script/vsts/release-branch-build.yml, script/vsts/upload-artifacts.js
<details><summary>Requirements for Adding, Changing, or Removing a Feature (from template)</summary>
* The pull request must contribute a change that has been endorsed by the maintainer team. See details in the template below.
* The pull request must update the test suite to exercise the updated functionality. For guidance, please see <https://flight-manual.atom.io/hacking-atom/sections/writing-specs/>.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see <https://github.com/atom/.github/tree/master/CONTRIBUTING.md#pull-requests>. …
=> Set up Azure DevOps config files to look for our fork, not upstream, enable automated releases

script/vsts/platforms/templates/bootstrap.yml
<details><summary>Requirements for Contributing a Bug Fix (from template)</summary>
* The pull request must only fix an existing bug. To contribute other changes, you must use a different template. You can see all templates at <https://github.com/atom/.github/tree/master/.github/PULL_REQUEST_TEMPLATE>.
* The pull request must update the test suite to demonstrate the changed functionality. For guidance, please see <https://flight-manual.atom.io/hacking-atom/sections/writing-specs/>.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see …
=> CI: GITHUB_TOKEN to fix vscode-ripgrep downloading issues

script/test, script/vsts/platforms/macos.yml, script/vsts/platforms/templates/test.yml, script/vsts/platforms/windows.yml, src/main-process/start.js
This:
- allows requesting any tests on any operating system
- parallelizes core renderer tests by using separate child processes for each file. 
- runs core renderer tests and packages tests in parallel using async.parallel. So if one of the tests goes in timeout, the others will continue to run. This speeds up running the tests by a lot! 🚀 
- allows rerunning only the failed tests rather than restarting the whole CI.
- On Windows, runs core renderer tests using two Azure agents. This in addition to double the overall test speed, will allow rerunning the failed ones in case some fail due to timeouts.
The CI passes
N/A
=> Parallelize Tests

script/test
This is a patch for #50 that collects the console log and prints it at the end.
=> collect console log in renderer tests

src/package.js
This allows loading the packages that are Es module and export their function wrapped in a default object. This is the case for any package that uses Babel 6, Babel 7, or other modern compilers for transpiling their package.
The behavior of ES6 is to use `exports.default = ....` for exporting something as default. 
This is equal to using `module.exports = ....` or `module.exports = {...}`.
In ES6 requiring the modules that exported like need explicitly calling `.default`
```js
const x = require(module).default // require(module) is wrong
```
`_require` function in this pull request checks if `default` property exists and returns what it is inside it instead of returning the useless module itself (which will not have the activate function for the package). 
`_require` function checks this …
=> support ES6 default require for packages

script/vsts/nightly-release.yml, script/vsts/pull-requests.yml, script/vsts/release-branch-build.yml
* The pull request must only affect performance of existing functionality. To contribute other changes, you must use a different template. You can see all templates at <https://github.com/atom/.github/tree/master/.github/PULL_REQUEST_TEMPLATE>.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see <https://github.com/atom/.github/tree/master/CONTRIBUTING.md#pull-requests>.
Run GetReleaseVersion (the first step) and the "Release"/"Upload Artifacts" (the last step on the Nightly/Release Branch pipelines) on `ubuntu-latest`. This alone …
=> CI: Faster GetReleaseVersion and Release/Upload Artifacts jobs

src/package-manager.js
This is a fix for https://github.com/atom/atom/pull/20899. It follows symbolic links and checks if they are a directory (`fs.isDirectorySync` does that internally). 
This only uses `fs.isDirectorySync` for symbolic links and still has higher performance compared to using this function for everything. `fs.dirent` is faster compared to `fs.stat`.
- Make a symbolic link from a folder to `.atom/packages`
- This change now detects if that symbolic link is a directory. Previous pull request did not
- Fix the issue that symbolic links are not detected as packages in the previous nightly.
https://github.com/atom/atom/pull/21065
=> detect symbolic link packages

src/main-process/atom-window.js
This enables the possibility of multithreading in Atom as stated in Electron documentation. It allows using Node features in WebWorkers.
https://www.electronjs.org/docs/tutorial/multithreading
This allows offloading the parts of the code that are blocking the main thread to another thread, which can result in a huge performance gain.
N/A
N/A
- CI passes
- Using the built Atom
- Now Atom allows using the multi-threading features of Nodejs
=> enable multi-threading on Atom

script/vsts/get-release-version.js, script/vsts/lib/release-notes.js, script/vsts/nightly-release.yml, script/vsts/platforms/linux.yml, script/vsts/platforms/windows.yml, script/vsts/pull-requests.yml, script/vsts/release-branch-build.yml, script/vsts/upload-artifacts.js
<details><summary>Requirements for Contributing a Bug Fix (from template)</summary>
* The pull request must only fix an existing bug. To contribute other changes, you must use a different template. You can see all templates at <https://github.com/atom/.github/tree/master/.github/PULL_REQUEST_TEMPLATE>.
* The pull request must update the test suite to demonstrate the changed functionality. For guidance, please see <https://flight-manual.atom.io/hacking-atom/sections/writing-specs/>.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see …
=> Fix miscellaneous ci issues

script/vsts/nightly-release.yml, script/vsts/platforms/templates/get-release-version.yml, script/vsts/pull-requests.yml, script/vsts/release-branch-build.yml
<details><summary>Requirements for Adding, Changing, or Removing a Feature (from template)</summary>
* The pull request must contribute a change that has been endorsed by the maintainer team. See details in the template below.
* The pull request must update the test suite to exercise the updated functionality. For guidance, please see <https://flight-manual.atom.io/hacking-atom/sections/writing-specs/>.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see <https://github.com/atom/.github/tree/master/CONTRIBUTING.md#pull-requests>. …
=> CI: Move GetReleaseVersion to its own template

apm/package-lock.json, apm/package.json
Helps with #44 
Use a fork of apm that's updated more frequently. By the same maintainers working on this fork of Atom. This fork is somewhat conservatively updated with needed fixes/dependency updates, and quality of life improvements.
Right now, the changes are limited to:
- Newer bundled Node (that exactly matches the version of Node that Electron 6 is based on, which we ship at this fork of Atom).
- Better support for Visual Studio 2017 and newer
- Normalized line endings (`CR/LF`) so that releases can be properly published from a Windows machine.
<details><summary>See the Changelogs:</summary>
- https://github.com/atom-ide-community/apm/releases/tag/2.5.0-atomic.2
- No change line-endings fix: https://github.com/atom-ide-community/apm/releases/tag/2.5.0-atomic.2.1
- …
=> Switch apm to @atom-ide-community/atom-package-manager

script/vsts/nightly-release.yml, script/vsts/platforms/templates/preparation.yml, script/vsts/platforms/windows.yml, script/vsts/release-branch-build.yml
This uses MSVC 2019 to build Atom on Windows. It does this on the windows-2019 image in Azure. To test the backward compatibility, the built Atom is tested on windows-2016.
The tests pass. Extra tests are added to test the backward compatibility on older Windows.
none
- build Atom with MSVC 2019 on Windows. 
- use windows-2019 in the CI
=> Build Windows with MSVC 2019

CONTRIBUTING.md, packages/incompatible-packages/styles/incompatible-packages.less, script/vsts/nightly-release.yml, script/vsts/platforms/templates/bootstrap.yml, script/vsts/platforms/templates/cache.yml, script/vsts/platforms/templates/preparation.yml, script/vsts/release-branch-build.yml, src/package.js
Just merging in a few changes from upstream.
We have gone back to `npm install` vs `npm ci` for installing `script/vsts/node_modules` dependencies. There are so few dependencies there that it only saved about 5 seconds or so to use `npm ci`, and that's on average. It varies a fair amount. I can live with this, I suppose.
I might still like to revert that change, but that would be in a follow-up commit or PR. Keeping the "merge from upstream" PR clean, faithful to what changed upstream.
There were a couple of improved comments in the templates. And on macOS the system `npm` path is used, rather than the `npm` shipped with Node. (Still gets updated to the pinned version we set it to, though? I'll take a close look and double-check once CI starts for this PR.) I went with this, because it's …
=> Merge upstream master

script/vsts/platforms/templates/preparation.yml, script/vsts/platforms/windows.yml
This uses MSVC 2017 to build Atom on Windows. Performs the test on Win 2019.
This is a patch for #44 
Closes https://github.com/atom-ide-community/atom/issues/117
=> CI: Windows: Build with MSVC 2017 and test on 2019

script/test
This automatically detects the timed out tests and reruns them. 
This is much faster than rerunning the tests manually in Azure. This is because the rerunning happens at a low JavaScript level compared to CI reruns that need to set up the whole environment and rerun all the tests just because one was timed out.
The CI passes. The functions are commented with details.
N/A
=> Retry timed out steps automatically

script/vsts/release-branch-build.yml
https://github.com/atom-ide-community/atom/issues/1#issuecomment-663877340, follow-up to: https://github.com/atom-ide-community/atom/pull/66, which was re-worked and landed as https://github.com/atom-ide-community/atom/pull/99.
Fix a spot where we missed using the re-mapped S3 and PackageCloud env vars.
(For the condition where `IsSignedZipBranch` is true, we were still using the un-re-mapped variables. That would cause them to always be set to not-very-useful `$(VAR_NAME_HERE)` values. That oversight defeated our skipping mechanism. This patch makes skipping uploads to S3 and PackageCloud work properly again.)
None.
None.
See this passing CI run to confirm that it worked: https://dev.azure.com/atomcommunity/atomcommunity/_build/results?buildId=738&view=logs&j=fc7b8a14-4c68-54ee-1e90-04bf6 …
=> CI: Really skip uploading artifacts to S3

script/vsts/platforms/templates/preparation.yml, script/vsts/platforms/windows.yml
Use `BUILD_ARCH` everywhere. (Eliminate `buildArch`.)
I'm doing this rather than what we were doing before, which was setting `buildArch`, then setting `BUILD_ARCH` equal to `buildArch` and then using the value from `BUILD_ARCH`. This was unnecessarily complicated and 100% redundant.
None.
None.
CI passes. Node 32-bit is still used on the Windows 32-bit jobs, Node 64-bit is still used for the Windows 64-bit jobs. (`buildArch` and `BUILD_ARCH` haven't ever been set on OSes other than Windows.)
N/A
=> CI: Simplify redundant "buildArch" and "BUILD_ARCH" variables into one variable

script/vsts/platforms/templates/bootstrap.yml, script/vsts/platforms/templates/preparation.yml
- Don't update npm twice. Once is enough.
- Delete these redundant steps: `npm install -g npm-windows-upgrade` and `npm-windows-upgrade`.
- Keep the `npm install -g npm` command.
- The `npm install -g npm` command modifies the npm at `C:/npm/prefix/npm.cmd`. So we set the `NPM_BIN_PATH` environment variable to point to that path instead of `C:/hostedtoolcache/windows/node/[maj.min.patch]/x64/npm.cmd`, which is the install that `npm-windows-upgrade` modifies.
- Set the Python version in the "Common" (all OSes) section of preparation, rather than doing this only on Windows.
About 45 seconds is saved before bootstrapping/building on Windows, and another 45 seconds is saved in each Windows test job.
- Installing `npm-windows-upgrade` takes about 20 seconds
- Running `npm-windows-upgrade` …
=> CI: Simplify preparation on Windows, Use Python 3.8 on all OSes

script/bootstrap, script/build, script/config.js, script/lib/install-apm.js, script/lib/install-script-dependencies.js, script/lib/install-script-runner-dependencies.js, script/script-runner/package-lock.json, script/script-runner/package.json, script/vsts/platforms/templates/cache.yml
Run the bootstrap script on different threads in parallel:
- apm installation runs in parallel to installing script/ dependencies
- using JOBS env variable node-gyp is parallelized
Running this on a computer with multiple cores gives a good speedup.
Even in the CI with a processor with only [2 cores](https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series#dsv2-series).
For example, on Linux the bootstrap time is reduced from [7:30](https://dev.azure.com/atomcommunity/atomcommunity/_build/results?buildId=761&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=524bc222-c500-5ef6-2104-858d8102dde5) to [3:41](https://dev.azure.com/atomcommunity/atomcommunity/_build/results?buildId=818&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=524bc222-c500-5ef6-2104-858d8102dde5), …
=> Parallel Bootstrap

script/test
This is a patch for #122:
- It increases the number of retrying to 6
- It adds "Error Downloading Update: Could not get code signature for running application" to retry triggers
=> Retry timed out tests more

.github/rebase.yml
This allows updating a branch automatically by commenting `/rebase` on a pull request. This is helpful to update the old branches especially for the branches created by the dependency updater bots.
=> Update branch automatically using rebase bot

packages/about/lib/update-manager.js, packages/about/spec/update-manager-spec.js, script/lib/create-windows-installer.js, script/lib/update-dependency/git.js, script/lib/update-dependency/pull-request.js
Closes https://github.com/atom-ide-community/atom/issues/83
Replace various hard-coded URLs throughout the project with dynamic ones. Allows certain features to work with respect to forks, not strictly pointing at the upstream repository.
Set the following environment variables to override the defaults:
`REPO_OWNER`            (default: `atom`)
`MAIN_REPO`             (default: `atom`)
`NIGHLTY_RELEASE_REPO`  (default: `atom-nightly-releases`)
None.
None anticipated. The original values are there as defaults.
CI should pass.
N/A
=> Update hard-coded GitHub URLs to be dynamic

script/lib/create-debian-package.js, script/vsts/platforms/templates/preparation.yml
This PR speeds up the build process of dpkg-deb on the Linux machines (by about 3 min):
- It uses `sudo` when available instead of `fakeroot`
- It does not compress the artifacts internally unless we are on a release/nightly branch. 
Before changes (16 min and 38 seconds): https://dev.azure.com/atomcommunity/atomcommunity/_build/results?buildId=878&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=cccdf131-0893-5d7b-ccea-9ccfc8953f95
After changes(13min and 18seconds): https://dev.azure.com/atomcommunity/atomcommunity/_build/results?buildId=879&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=cccdf131-0893-5d7b-ccea-9ccfc8953f95
- Faster builds by dpkg-deb on Linux
=> linux dpkg-deb: speed up build

script/lib/include-path-in-packaged-app.js
This excludes `node_modules/*/tests?` from being included in the final packaged Atom. This does not affect any testing as it only excludes these in the final Atom executable.
- Results in a smaller packaged app which means that loading it will be faster.
- The build time will be faster since the build scripts don't need to copy/transpile/compile the tests 
The tests are not needed in the packaged Atom. There was already a script for jest tests (__tests__), but that does not capture the tests by other libraries.
=> exclude test folders from the packaged app

script/build, script/config.js, script/lib/install-apm.js, script/lib/install-script-runner-dependencies.js, script/lib/prebuild-less-cache.js, script/lib/transpile-babel-paths.js, script/lib/transpile-coffee-script-paths.js, script/lib/transpile-cson-paths.js, script/lib/transpile-packages-with-custom-transpiler-paths.js, script/lib/transpile-peg-js-paths.js
This PR parallelizes the transpiling part of the build, so they run on different threads. This is built on top of #21308 and uses threads as its script-runner. The changes to the scripts/lib are very minimal. The build script is changed to support running the threads. 
Note: This PR is part of the series that speed up the build/bootstrap of Atom #21308 #21342 #21398 and more PRs that are coming (such as parallelizing copy assets, clean, etc). See https://github.com/atom-ide-community/atom/pull/155.
The local builds/CI pass all the tests,
Results in a faster building of Atom locally or in the CI.
Faster building by using threads for transpiling.
=> Parallel transpiling (build)

script/bootstrap, script/build, script/clean, script/lib/clean-caches.js, script/lib/clean-dependencies.js, script/lib/clean-output-directory.js
This parallelizes clean by using parallel asynchronous execution of each clean task.
The clean task is much faster (~30s) in the offline situations since they do not wait for each other to get finished.
N/A
Run `./script/clean`
=> Parallel Clean

src/atom-environment.js, src/command-registry.js, src/initialize-benchmark-window.js, src/initialize-test-window.coffee, src/pane-element.js, src/tooltip.js, src/workspace-element.js
This uses `{capture: true}` instead of `true` in `addEventListeners`.
Based on the docs `true` is equal to `{capture: true}`
> In older versions of the DOM specification, the third parameter of addEventListener() was a Boolean value indicating whether or not to use capture. Over time, it became clear that more options were needed. Rather than adding more parameters to the function (complicating things enormously when dealing with optional values), the third parameter was changed to an object that can contain various properties defining the values of options to configure the process of removing the event listener.
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Improving_scrolling_performance_with_passive_listeners
Using the `{}` syntax is the standard modern …
=> Use capture true instead of boolean in addEventListener

static/core-ui/text-editor.less
This adds more [CSS containment](https://drafts.csswg.org/css-contain/#contain-property) to tree-view CSS classes. This results in performance improvements by giving the hint to the browser that the size/paint/layout of these elements does not affect other elements around them.
I have added the CSS containment for each class selectively by testing all the functionalities. As you see, these do not change the functionality.
Improves the performance and responsiveness of the text editor. It has improved scrolling performance. The datatips and decorations are rendered faster than before. 
The reason is that the browser will not need to recalculate the styles on clicks, scrolling, drag-drop, during the loading, etc.
Quoting [CSS specifications](https://drafts.csswg.org/css-contain/#contain-prop …
=> performance: add more CSS containment to text-editor

src/text-editor.js
This PR refactors the codes that were responsible for updating different parts of TextEditor out of `update` function, and, then, it uses those refactored functions directly, which bypasses the loop and switch case inside `update`.
`finishUpdate` is also refactored that allows finishing updating of TextEditor from inside themselves without the need for creating objects outside and passing them in.
- This reduces the complexity of the update algorithm for those that are updated directly (`O(n^2)`->`O(1)`). This removes the overhead of checking for the given value against the keys in switch-case, and it also removes the overhead of the for-loop. Directly calling these functions is similar to the compile-time method dispatch used in other languages like C++. The previous method was a runtime …
=> Refactor TextEditor updating 

README.md
Since the upstream is sunsetting but it seems development is continuing here I thought it might be a good idea to update the readme to be more clear with the note at the top that it means the upstream Atom repo's and not the atom-community ones or whatever this may end up being called in the future.
Anyone can change this wording because I'm not sure I've done it justice but it feels like this is a first step that needs to be done whenever possible. I'm putting this here as a starting point for this and there's probably other edits that need to be done maybe for now importing the wiki/docs to a github wiki?
=> Updating readme to be more clear w/upstream sunset

script/vsts/platforms/templates/preparation.yml
We are using older Node 12.16.3 in CI.
(Which coincidentally matches Electron 10... but I think that's just a coincidence of updating to the latest Node LTS 12 version at around the same time Electron 10 came out.)
Using newer Node in the same line is better for bug fixes. Using the same version of Node our Electron version is based off of theoretically has some benefits, although I'm not super clear on what they are, there's also no harm in it other than missing out on even newer releases (for example 12.22.12.)
Update Node in CI from 12.16.3 to the slightly newer 12.18.3, which [matches Electron 11](https://www.electronjs.org/releases/stable?version=11&page=6#11.0.0) as currently used in the fork's `master` branch.
None considered.
None anticipated.
If CI passes, this should be strictly …
=> CI: Bump Node to 12.18.3 to match Electron 11

src/main-process/main.js, src/main-process/parse-command-line.js, src/main-process/start.js
**Note**: This was originally PR https://github.com/atom/atom/pull/25442, by @claytonrcarter over at upstream.
I have personally tested the changes and found that they work.
I like these changes, and I got permission to re-post them as a PR here to the community fork of Atom. (See: https://github.com/atom/atom/pull/25442#issuecomment-1159737573).
**Please don't push any changes directly to his branch.** If this needs any changes, please let me (@DeeDeeG) know, and I'll open a new PR off of my own fork, or post the branch to the community fork directly, so we can post whatever needed fixes without disturbing the original author's original branch (and indirectly affect the original author's PR at upstream).
To repeat: **DO NOT PUSH ANYTHING TO THIS PR'S BRANCH. THIS PR IS TRACKING THE …
=> Fix usage message

script/package-lock.json, script/package.json
Fixes: https://github.com/atom-community/atom/issues/363
Bump minidump from 0.22.0 to 0.23.0 in script/package.json
None
None expected.
https://github.com/atom-community/atom/issues/363 seems to be fixed by updating `minidump` to the latest version, in `script/package.json`. 0.22.0 --> 0.23.0
<details>
I tested this in a fresh install of the latest [Manjaro Linux](https://manjaro.org/), which is a type of Arch Linux. I got the same error situation as @DAC324 reported.
I tried debugging it. `dump_syms` had blank output on stdout and stderr, so that is why there was no detailed or helpful error message being printed. The binary being spawned really had no output. I think it's fixed by this upstream commit of breakpad? ["avoid dump_syms crashing if selected arch is not …
=> deps: Bump minidump (0.22.0 to 0.23.0) in script/

script/vsts/platforms/windows.yml
The Windows 2016 image has been/will be deprecated as of today. https://github.com/actions/virtual-environments/issues/5403
Small update required to keep the CI running.
=> Change Windows Build image - 2016 -> 2019

README.md
Fixing the retirement badge for clarity to avoid confusion. Since it should be clear(until we rename/rebrand eventually) that it's not us retiring but upstream atom.
=> Update retirement badge for clarity

script/lib/dump-symbols.js
Dumping the symbols is not essential for the build. It is used for debugging purposes when something fails.
Fixes #363
=> fix: ignore the errors caused by dumping the symbols on non-windows

package.json, packages/language-c/package.json, packages/language-html/package.json, packages/language-java/package.json, packages/language-json/package.json, packages/language-python/package.json, packages/language-ruby/package.json, packages/language-rust-bundled/package.json, packages/language-shellscript/package.json, packages/language-typescript/package.json
Please, merge after this PR otherwise grammars will break: https://github.com/atom-community/atom/pull/399
This PR bumps tree-sitter to a recent version. It also uses "NPM's tree sitter", not an Atom/git specific one.
I know this code works with Electron 12. Unfortunately, `./script/bootstrap` and friends do not work on my machine, so I have no way of testing if the "current way" of building Atom also works...
Also, this PR is basically https://github.com/atom-community/atom/pull/386, but splitted into bumping tree-sitter. I'll open another bumping Electron (but it's also dependent on this one, unfortunately)
=> Bump tree sitter

package.json
Follow-up to https://github.com/atom-community/atom/pull/418.
<details><summary>Bug details (click to expand)</summary>
https://github.com/atom-community/atom/pull/418 updated the `packageDependencies:` version of the snippets package, but not the `dependencies:` version. (This works fine if running `apm ci`, like CI does. CI runs would not have detected this problem.)
The latest git commit of the community fork of the snippets package, as added to core's package.json in https://github.com/atom-community/atom/pull/418, has had its version bumped to 1.6.0 at some point. The core editor's `dependencies` version of snippets still says 1.5.1.
If running `apm install`, apm apparently notices the versions don't match, and overwrites it all with the "1.5.1" version listed in `dependencies`. …
=> package.json: Update "snippets" dependencies version to match packageDependencies version

SUPPORT.md
* The pull request must only contribute documentation (for example, markdown files or API docs). To contribute other changes, you must use a different template. You can see all templates at <https://github.com/atom/.github/tree/master/.github/PULL_REQUEST_TEMPLATE>.
Add the GitHub Discussions link for Atom-Community rather than Atom's repository
N/A
=> Make GitHub Discussions link point to Atom Community and remove other support options

package-lock.json, package.json
Similar to https://github.com/atom-community/atom/pull/421. Misconfigured packageDependencies version for a package.
`packageDependencies` versions have to be a number `1.2.3` or a relative path `file:./path/to/package`. Otherwise, `apm install` complains and errors out.
I believe the version specs in `packageDependencies` of package.json can only be:
- version numbers (`1.2.3-something`)
- or relative paths (`file:./packages/[package_name_here]`).
Due to limitations in apm's `install` command.
Ran `script/bootstrap` and `apm install` commands locally. This PR fixes an error message:
```console
$ ./apm/node_modules/atom-package-manager/bin/apm install
Installing modules ✓
Installing find-and-replace@https://github.com/atom-community/find-and-replace/archive/refs/tags/v0.220.1.tar.gz ✗ …
```
=> deps: update packageDependencies entry for find-and-replace

docs/Installation.md
Following up on discussion in https://github.com/atom-community/atom/pull/456.
Add link to a nice binaries dashboard to the Installation.md instructions.
(Dashboard is originally by @autumnblazey, but not maintained by them anymore. atom-community org is welcome to fork the dashboard repo if there is a need to make updates.)
N/A
=> doc: Add binaries dashboard (install instructions)

script/vsts/nightly-release.yml, script/vsts/release-branch-build.yml, script/vsts/upload-artifacts.js
<details><summary>Requirements for Contributing a Bug Fix (from template, click to expand):</summary>
* The pull request must only fix an existing bug. To contribute other changes, you must use a different template. You can see all templates at <https://github.com/atom/.github/tree/master/.github/PULL_REQUEST_TEMPLATE>.
* The pull request must update the test suite to demonstrate the changed functionality. For guidance, please see <https://flight-manual.atom.io/hacking-atom/sections/writing-specs/>.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more …
=> Fix "Upload Artifacts" job in CI (makes CI pass)

docs/Installation.md
<details><summary><b>Requirements for Contributing Documentation</b> (from template, click to expand):</summary>
* The pull request must only contribute documentation (for example, markdown files or API docs). To contribute other changes, you must use a different template. You can see all templates at <https://github.com/atom/.github/tree/master/.github/PULL_REQUEST_TEMPLATE>.
</details>
This makes the first half of the Installation docs followable again.
The old link went down, and while a redirect would be possible, the atom-community org's forked version of the repo has deployed a fix that isn't deployed at the …
=> docs: Update URL for the CI (binaries) dashboard

apm/package-lock.json, apm/package.json
<details><summary><b>Requirements for Contributing a Bug Fix</b> (click to expand):</summary>
* The pull request must only fix an existing bug. To contribute other changes, you must use a different template. You can see all templates at <https://github.com/atom/.github/tree/master/.github/PULL_REQUEST_TEMPLATE>.
* The pull request must update the test suite to demonstrate the changed functionality. For guidance, please see <https://flight-manual.atom.io/hacking-atom/sections/writing-specs/>.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, …
=> apm: Update to v2.6.5-atomic.1.1
